def get_printer_profile():
    return {
          "default_firmware_retractions_zhop": False,
          "description": "Genuine Prusa Mk2/Mk2S With Multi-Material",
          "e_axis_default_mode": "require-explicit",
          "g90_influences_extruder": "use-octoprint-settings",
          "movement_speed": 10800.0,
          "origin_y": 0,
          "origin_x": 0,
          "priming_height": 0.75,
          "min_x": 0.0,
          "guid": "42d2f5ec-7cc8-4d65-aec8-9015ecff7db6",
          "retract_speed": 4800.0,
          "min_y": 0.0,
          "axis_speed_display_units": "mm-min",
          "auto_position_detection_commands": "",
          "abort_out_of_bounds": True,
          "name": "Prusa Mk2/Mk2S Multi Material",
          "min_z": 0.0,
          "z_hop_speed": 7200.0,
          "retract_length": 4.0,
          "xyz_axes_default_mode": "require-explicit",
          "snapshot_command": "snap",
          "override_octoprint_print_volume": False,
          "z_hop": 0.5,
          "detract_speed": 3000.0,
          "default_firmware_retractions": True,
          "printer_position_confirmation_tolerance": 0.001,
          "units_default": "millimeters",
          "max_y": 0.0,
          "max_z": 0.0,
          "auto_detect_position": False,
          "max_x": 0.0,
          "origin_z": 0
    }

